version: '2'
services:
  web:
    image: banka:latest
    command:  bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    links:
      - db
    environment:
      RAILS_ENV: production

  db:
    image: postgres:9.4.5
    volumes:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_DB: banka_production