---
# tasks file for pgsql

- name: Add PostgreSQL Repository
  sudo: yes
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ {{short_os_name}}-pgdg main' state=present

- name: Add Keys for PostgreSQL Repository
  sudo: yes
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present

- name: Update apt
  sudo: yes
  apt: update_cache=yes

- name: Install PostgreSQL Packages
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - libpq-dev
    - postgresql-{{ pgdb_version }}
    - postgresql-client-{{ pgdb_version }}
    - python-pygresql
    - python-psycopg2
  notify: restart postgresql

- name: set postgres password
  shell: sudo -u postgres psql -c "ALTER USER {{ pgdb_sudo_user }} PASSWORD '{{ pgdb_sudo_pass }}';"
  when: pgdb_sudo_pass != ''

- name: Create databases
  sudo: yes
  sudo_user: "{{ pgdb_sudo_user }}"
  postgresql_db: name={{ item }} state=present
  with_items: "{{ pgdb_databases }}"

- name: Create users
  sudo: yes
  sudo_user: "{{ pgdb_sudo_user }}"
  postgresql_user: name={{ item.user }} password={{ item.password }} db={{ item.database }} priv=ALL
  with_items: "{{ pgdb_users }}"

- name: Add pgcrypto extension
  sudo: yes
  sudo_user: "{{ pgdb_sudo_user }}"
  postgresql_ext: name=pgcrypto db={{ item }}
  with_items: "{{ pgdb_databases }}"

- name: Set correct pg_hba.conf with md5 access
  copy: src=pg_hba.conf dest=/etc/postgresql/{{ pgdb_version }}/main/pg_hba.conf owner=postgres group=postgres mode=0640
  notify: restart postgresql